name: Python package build and publish

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Performance
        run: bash .ci/performance.sh

      - name: Build sources
        run: bash .ci/build-linux-sdist.sh

      - name: Build manylinux Python wheels
        uses: RalfG/python-wheels-manylinux-build@v0.6.0-manylinux2014_x86_64
        with:
          python-versions: "cp37-cp37m cp38-cp38 cp310-cp310 cp311-cp311 cp312-cp312"
          build-requirements: "cython"

      - name: Publish wheels to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*-manylinux*.whl dist/*.tar.gz
